name: Push_Action

on:
  push:
    branches:
      -main

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v2
      -uses: dependabot/action@v2
    with:
      repo-token: ${{secrets.GITHUB_TOKEN }}
 
