name: CI/CD 

on:
  push: 
    branches:
    - main

jobs: 
  build:
    name: Push_to_main
    runs-on: ubuntu-latest
    steps:
      run:
        echo: "::warning :: Um codigo foi submetido a branch Master"
    
